export enum Services {
  PRODUCTS_SERVICE = 'PRODUCTS_SERVICE',
  USERS_SERVICE = 'USERS_SERVICE',
  ORDERS_SERVICE = 'ORDERS_SERVICE',
  PAYMENTS_SERVICE = 'PAYMENTS_SERVICE',
}
export const services = [
  Services.PRODUCTS_SERVICE,
  Services.USERS_SERVICE,
  Services.ORDERS_SERVICE,
  Services.PAYMENTS_SERVICE,
];